# Generated by Django 3.2 on 2021-05-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHCOOL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Title', models.CharField(max_length=100)),
                ('Service_Photo', models.FileField(upload_to='Services')),
                ('Service_Description', models.TextField()),
            ],
        ),
    ]
